"""
COUNTERFACTUAL_TO_REALITY_GAP_MATRIX.csv -- second-pass audit of the
COUNTERFACTUAL_MASTER_THEORY_OF_EVERYTHING manuscript, separating each
load-bearing component into what is real (repository- or established-
physics-supported) versus invented for the fiction.
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent

ROWS = [
    dict(component="Graph Laplacian L=D-W, eigendecomposition",
         counterfactual_result="Foundational object of the entire master equation (Sec. 2)",
         repository_support="YES -- compiler/backends/graph_laplacian.py, VERIFIED, executed and tested",
         established_physics_support="YES -- standard spectral graph theory (Chung 1997)",
         new_assumption_required="NO", actual_derivation_exists="YES (in this project's real code)",
         status="REAL, already canonical prior to any campaign"),
    dict(component="Spectral square root D+=sqrt(L)",
         counterfactual_result="Used as the 'Dirac-type operator' feeding the master equation (Sec. 2, Lemma 1)",
         repository_support="PARTIAL -- Master Equation Codex names this 'the Dirac operator' with no justification",
         established_physics_support="YES -- functional square root of a PSD operator is standard linear algebra",
         new_assumption_required="YES -- that this is a physically meaningful Dirac-type operator (Clifford/spinor structure not shown)",
         actual_derivation_exists="PARTIAL (the square root itself: yes; its physical interpretation: no)",
         status="Mathematically real; physical naming is a creative extrapolation"),
    dict(component="Persistence Selection Principle (Counterfactual Axiom 1)",
         counterfactual_result="Closes SELECTION-SIGMA, makes GRAPH-G-SEED a derived rather than postulated object (Sec. 2)",
         repository_support="WEAK -- inspired by Master Equation Codex's own unproven A*=argmax(Pi/S) assertion",
         established_physics_support="NO", new_assumption_required="YES -- existence and uniqueness of the argmax is asserted, not proved",
         actual_derivation_exists="NO",
         status="FICTIONAL -- the single largest invented axiom in the manuscript"),
    dict(component="Spectral triple admissibility of (D+,L) (Counterfactual Axiom 2)",
         counterfactual_result="Licenses applying the real spectral action to this project's graph Laplacian (Sec. 3)",
         repository_support="NO", established_physics_support="the AXIOMS THEMSELVES are real and well-defined (Connes)",
         new_assumption_required="YES -- that (D+,L) satisfies them is asserted, not checked",
         actual_derivation_exists="NO",
         status="FICTIONAL -- a real mathematical bar that was never actually cleared or even tested"),
    dict(component="Chamseddine-Connes spectral action S[D]=Tr f(D/Lambda)+<psi,Dpsi>",
         counterfactual_result="Selected as the master equation (Sec. 4)",
         repository_support="YES -- already registered as NCG-BRIDGE-EXTERNAL-REFERENCE, quoted correctly in DTC-RP-004",
         established_physics_support="YES -- real, published, peer-reviewed physics (Chamseddine-Connes 1996/2006)",
         new_assumption_required="NO (the equation itself); YES (that it applies to this project's D+)",
         actual_derivation_exists="YES for the real theory's own conventional spin-manifold application; NO for this project's graph-native substitution",
         status="REAL equation, FICTIONAL application"),
    dict(component="Seeley-DeWitt heat-kernel expansion (a0,a2,a4 coefficients)",
         counterfactual_result="Generates cosmological-constant, Einstein-Hilbert, and Yang-Mills/Higgs terms (Sec. 5)",
         repository_support="referenced only in the NCG literature-summary PDFs, not independently computed anywhere in this project",
         established_physics_support="YES -- standard, well-established asymptotic expansion technique",
         new_assumption_required="YES -- that a2 for THIS project's operator equals a genuine 4D Riemannian scalar curvature, which requires the (unachieved) FC-005 continuum limit",
         actual_derivation_exists="NO (never computed for this project's own operator)",
         status="REAL technique, FICTIONAL that it applies here"),
    dict(component="Heat-trace / Euclidean partition-function identity Z(beta)=Tr e^(-beta D+^2)",
         counterfactual_result="Basis of the Quantum and Thermodynamic Sectors (Sec. 6, 10, Lemma 2)",
         repository_support="the heat-trace side is real and executed (compiler/backends/heat_flow.py)",
         established_physics_support="YES -- standard, exact mathematical identity in Euclidean QFT/stat mech",
         new_assumption_required="NO for the identity itself; YES for treating D+^2 as THE physical Hamiltonian of the universe",
         actual_derivation_exists="YES for the identity; NO for the physical claim built on it",
         status="REAL identity, FICTIONAL physical scope"),
    dict(component="'Quantum mechanics is the continuum limit of the graph spectrum' (used implicitly in Sec. 6)",
         counterfactual_result="Assumed to hold generally, enabling full QM/QFT recovery",
         repository_support="explicitly CONTRADICTED -- this project's own real FC-005 execution found convergence for only 4 of 15 tested modes",
         established_physics_support="NO", new_assumption_required="YES -- directly overrides a real, already-collected negative finding",
         actual_derivation_exists="NO -- actively falsified in the real Master TOE Derivation Campaign",
         status="FICTIONAL, and known to conflict with real project evidence"),
    dict(component="Einstein field equations Gmunu+Lambda gmunu=(8piG/c^4)Tmunu",
         counterfactual_result="Recovered exactly in form as the Gravity Sector (Sec. 7)",
         repository_support="the equation itself appears throughout the repository (restated, never derived)",
         established_physics_support="YES -- real, established General Relativity (Einstein 1915/1917)",
         new_assumption_required="NO for the equation; YES for the claim that it follows from the master equation, which requires the unproven a2<->R identification (see above)",
         actual_derivation_exists="NO new derivation; the equation is restated, not derived, even within the fiction",
         status="REAL equation, FICTIONAL derivation chain"),
    dict(component="G2=Aut(octonions) and G2's maximal subgroup SU(3)",
         counterfactual_result="Building block of the Gauge Sector's group-theory argument (Sec. 8)",
         repository_support="referenced (unconstructed) in DTC COMPILER.docx and SEIT v2",
         established_physics_support="YES -- genuine, correct, well-known facts in Lie theory",
         new_assumption_required="NO (these two facts are simply true)",
         actual_derivation_exists="YES (as pure group theory, independent of any physics application)",
         status="REAL mathematics, correctly used as an ingredient"),
    dict(component="Spin(8) triality (outer automorphism group S3)",
         counterfactual_result="Second building block of the Gauge Sector's group-theory argument (Sec. 8)",
         repository_support="referenced (unconstructed) in DTC COMPILER.docx",
         established_physics_support="YES -- genuine, correct, well-known fact in Lie theory",
         new_assumption_required="NO", actual_derivation_exists="YES (as pure group theory)",
         status="REAL mathematics, correctly used as an ingredient"),
    dict(component="G2/Spin(8) intersection = SU(3)xSU(2)xU(1)",
         counterfactual_result="Central claim of the Gauge Sector: this intersection IS the Standard Model gauge group (Sec. 8)",
         repository_support="NO -- this specific intersection is never constructed anywhere in the repository (per compiler/historical/register.py's own audit and this campaign's independent re-confirmation)",
         established_physics_support="an octonion/Spin(8) route to the Standard Model is a real, serious research direction (Furey, Dixon) but this exact construction is not reproduced from that literature",
         new_assumption_required="YES -- the central, load-bearing, entirely invented step of the entire Gauge Sector",
         actual_derivation_exists="NO",
         status="FICTIONAL -- the weakest link in the Gauge Sector, explicitly flagged as such in the manuscript itself"),
    dict(component="SU(3)xSU(2)xU(1) as the real Standard Model gauge group",
         counterfactual_result="Preserved throughout as the target the fiction claims to reach",
         repository_support="preserved per this campaign's own and the prior campaign's explicit governing instruction",
         established_physics_support="YES -- real, independently confirmed 20th-century physics, unrelated to anything in this repository",
         new_assumption_required="NO", actual_derivation_exists="YES (real, external, not from this project)",
         status="REAL and ESTABLISHED, but NOT a consequence of this manuscript or this repository"),
    dict(component="Mass formula mn=m0*sqrt(lambda_n)",
         counterfactual_result="Proposed mechanism for particle generations (Sec. 9)",
         repository_support="verbatim from Master Equation Codex eq. 5.1, an unproven assertion",
         established_physics_support="NO known established physics uses this specific relation",
         new_assumption_required="YES", actual_derivation_exists="NO",
         status="FICTIONAL; deliberately left symbolic (no numbers fit), unlike the real corpus's own alpha/m_e claims"),
    dict(component="Clausius-Duhem thermodynamic apparatus (dU, q^mu, Delta S>=0)",
         counterfactual_result="Claimed to follow from coarse-graining the master equation (Sec. 10)",
         repository_support="the target equations appear in FORWARD_MDCL_COMPILER_SPEC.md as the canonical (unbuilt) TRC target",
         established_physics_support="YES for the equations themselves (standard continuum thermodynamics)",
         new_assumption_required="YES -- the claimed derivation from the spectral action is entirely unconstructed",
         actual_derivation_exists="NO",
         status="REAL target equations, FICTIONAL that this manuscript derives them"),
    dict(component="Friedmann equations / cosmological constant identification (Sec. 11)",
         counterfactual_result="Claimed recovery of cosmology, with Lambda tied to a0",
         repository_support="only DESI's own fiducial LambdaCDM parameters are used as pipeline input anywhere in this project, never derived",
         established_physics_support="the Friedmann equations themselves are real, established physics",
         new_assumption_required="YES -- the magnitude-matching identification is asserted with no mechanism (this fiction inherits, not solves, the real cosmological-constant problem)",
         actual_derivation_exists="NO", status="REAL target equations, FICTIONAL derivation and magnitude match"),
    dict(component="Counterfactual FC-005 Closure / bias-corrected kernel K_corrected",
         counterfactual_result="Proposed mechanism to extend discrete-to-continuum convergence to all modes (Sec. 12)",
         repository_support="grounded in the REAL diagnostic pattern found in FC005_N_SCALING_REPORT.md (higher modes fail via eigenvalue-crossing false positives)",
         established_physics_support="higher-order kernel bias-correction techniques of this general TYPE exist in the real graph-Laplacian convergence literature (e.g. Singer 2006), but the SPECIFIC correction proposed here is invented",
         new_assumption_required="YES -- the specific coefficient c2 and the claim it suffices to fix convergence are entirely invented, never computed or tested",
         actual_derivation_exists="NO", status="FICTIONAL, explicitly and repeatedly labeled as such in the manuscript itself, per the user's explicit instruction"),
    dict(component="Nambu-Goto / Polyakov string action as a 'dual representation' of the master equation",
         counterfactual_result="Speculative string-theory crosswalk (Appendix C)",
         repository_support="the actions themselves are real, correctly extracted with provenance in the prior L0-ST campaign phase",
         established_physics_support="the actions are real; the claimed DUALITY between them and this manuscript's spectral action is NOT established anywhere in real physics",
         new_assumption_required="YES -- the duality claim is pure speculation with no constructed map",
         actual_derivation_exists="NO",
         status="REAL equations quoted correctly, FICTIONAL and explicitly labeled speculative duality claim"),
    dict(component="Classical Virasoro algebra vs. graph-Laplacian spectrum relationship",
         counterfactual_result="Appendix C explicitly does NOT claim these are related",
         repository_support="the prior L0-ST campaign found them mathematically INDEPENDENT (different mathematical categories)",
         established_physics_support="consistent with the real, established distinction between Lie-algebra generators and matrix eigenvalues",
         new_assumption_required="NO -- this row records a real finding preserved, not overturned, by the fiction",
         actual_derivation_exists="YES (the real independence finding)",
         status="REAL finding, correctly NOT overturned by this manuscript"),
    dict(component="Overall Counterfactual Master Theorem",
         counterfactual_result="Conditional theorem: IF Propositions 1+2 AND FC-005 closure AND the gauge-group intersection all hold, THEN GR+SM+QFT+thermo+cosmology follow from one action",
         repository_support="its individual real-math ingredients are repo-adjacent (spectral action reference, string literature, graph Laplacian)",
         established_physics_support="the PROOF METHOD (Seeley-DeWitt term-by-term decomposition) is real and correctly applied to the hypotheses",
         new_assumption_required="YES -- all three bracketed hypotheses are unproven, undemonstrated, and (for FC-005 and the gauge intersection) actively in tension with this project's own real evidence",
         actual_derivation_exists="NO -- explicitly stated in the manuscript itself as 'only as strong as its three hypotheses'",
         status="Honestly conditional FICTION; the manuscript itself does not claim otherwise"),
]


def main():
    fieldnames = ["component", "counterfactual_result", "repository_support",
                  "established_physics_support", "new_assumption_required",
                  "actual_derivation_exists", "status"]
    with (ROOT / "COUNTERFACTUAL_TO_REALITY_GAP_MATRIX.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for row in ROWS:
            w.writerow(row)
    print(f"wrote COUNTERFACTUAL_TO_REALITY_GAP_MATRIX.csv ({len(ROWS)} rows)")


if __name__ == "__main__":
    main()
