"""Writes PEER_REVIEW_STATUS_MATRIX.md from a computed protocol matrix
(compiler/protocol/protocol_matrix.py). Pure formatting -- every number
and status in this file is read from the matrix entries it is given, not
recomputed or re-derived here.
"""
from __future__ import annotations

from pathlib import Path

from compiler.protocol.protocol_matrix import NO_ARTIFACT, ProtocolMatrixEntry, layer_summary


def render_protocol_matrix_report(entries: list[ProtocolMatrixEntry]) -> str:
    lines: list[str] = []
    lines.append("# PEER_REVIEW_STATUS_MATRIX.md")
    lines.append("")
    lines.append(
        "Crosswalk of the \"Candidate Universal Theory Compiler -- Protocol Matrix v1.0\" "
        "taxonomy (a design proposal discussed and agreed for this repository) against this "
        "repository's REAL canonical MDCL registries. Every status below is read directly off "
        "a real Object, Transformation, Chainlink, self-audit result, registered Protocol, or "
        "on-disk document THIS compiler run produced -- see "
        "compiler/protocol/protocol_matrix.py's `_CORRESPONDENCES` dict for the exact, "
        "explicit, hand-checked mapping. A protocol with no entry there is reported as "
        f"`{NO_ARTIFACT}`, not silently omitted and not guessed at."
    )
    lines.append("")
    lines.append(
        "**Scope**: this crosswalk reads only the registries `python3 -m compiler.run_compiler` "
        "itself produces. Real work exists elsewhere in this repository "
        "(`scientific_corpus/derivation/`, `seit_lang/`) that is not registered into these "
        "canonical registries; where that matters for a specific protocol, the per-protocol "
        "note below says so explicitly rather than reaching outside this run's own artifacts."
    )
    lines.append("")
    lines.append("## Layer summary")
    lines.append("")
    lines.append("| Layer | Name | Reviewer question | Requested status | Protocols | With real backing | No corresponding artifact |")
    lines.append("|---|---|---|---|---|---|---|")
    for row in layer_summary(entries):
        lines.append(
            f"| {row['layer']} | {row['layer_name']} | {row['reviewer_question']} | "
            f"{row['requested_status']} | {row['n_protocols_total']} | "
            f"{row['n_with_real_backing']} | {row['n_no_corresponding_artifact']} |"
        )
    lines.append("")
    lines.append(
        "\"With real backing\" means the protocol resolved to a real registry artifact -- it "
        "does **not** mean that artifact's status is VERIFIED or DERIVED. A protocol counts as "
        "backed even when the real artifact's status is FAIL, FALSIFIED, or OPEN: what this "
        "column measures is whether the question is answered by something real and checkable, "
        "not whether the answer is favorable."
    )
    lines.append("")
    lines.append("## Full protocol matrix")
    lines.append("")
    lines.append("| Protocol | Layer | Family/Target | Computed status | Evidence |")
    lines.append("|---|---|---|---|---|")
    for e in entries:
        evidence = e.evidence.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {e.protocol_id} | {e.layer} | {e.family_or_target} | {e.computed_status} | {evidence} |")
    lines.append("")
    lines.append(
        "---\n*Generated by compiler/protocol/write_protocol_matrix_report.py from the exact "
        "registries this compiler run produced. No status above was asserted from prose.*"
    )
    return "\n".join(lines) + "\n"


def write_protocol_matrix_report(entries: list[ProtocolMatrixEntry], out_path: Path) -> None:
    out_path.write_text(render_protocol_matrix_report(entries))
